### ISSUE TITLE
Script for Tencent.QQ.NT needs to be updated

### ISSUE THREAD

**Issue by stevenlele** [SpecterShell/Dumplings#11]
https://github.com/SpecterShell/Dumplings/blob/5fe9f5f6fc92f1f7beced81d8a8f0f3db5fa6877/Tasks/Tencent.QQ.NT/Script.ps1#L1

This file is no longer updated. You need to get https://im.qq.com/pcqq/index.shtml and extract the latest config URL.

```js
// 此处是模版变量，在流水线上会被替换掉的
var rainbowConfigUrl = "https://qq-web.cdn-go.cn/im.qq.com_new/4d7d217d/202408081656/windowsDownloadUrl.js?t=1723107375635";
if(rainbowConfigUrl.startsWith("{{")) {
  rainbowConfigUrl = "//cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/windowsDownloadUrl.js";
}
```

https://github.com/SpecterShell/Dumplings/blob/5fe9f5f6fc92f1f7beced81d8a8f0f3db5fa6877/Tasks/Tencent.QQ.NT/Script.ps1#L40

Release notes URL should be extracted from https://im.qq.com/pcqq/support.html:

```js
// 此处是模版变量，在流水线上会被替换掉的
var rainbowConfigUrl = "https://qq-web.cdn-go.cn/im.qq.com_new/4d7d217d/202408081656/windowsQQVersionList.js?t=1723107375635";
if(rainbowConfigUrl.startsWith("{{")) {
  rainbowConfigUrl = "//cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/windowsQQVersionList.js";
}
```

(or just compute it from the download link - they have the same prefix)

**Comment by SpecterShell** [comment]
Fixed
