### ISSUE TITLE
Store release time in publisher local time zone

### ISSUE THREAD

**Issue by stevenlele** [SpecterShell/Dumplings#14]
Currently the automation converts release time in CST to UTC and stores them:

https://github.com/search?q=repo%3ASpecterShell%2FDumplings%20%22China%20Standard%20Time%22&type=code

Some other tasks parses a UNIX timestamp and stores it in UTC:

https://github.com/search?q=repo%3ASpecterShell%2FDumplings+ConvertFrom-UnixTimeSeconds&type=code

Since WinGet only supports a local `ReleaseDate` (`yyyy-MM-dd`), you should store release time in that format and in CST for Chinese specific packages wherever possible. Otherwise, if that release time is before 08:00, it will end up in the WinGet manifest as the previous day, which contradicts to what most users (who are in China) see on the official webpage or in the program.

**Comment by SpecterShell** [comment]
Nope.

In most packages, the release time is stored as a Unix timestamp defaulted to UTC timezone (such as `1723726800`), a ISO datetime string in UTC timezone (such as `2024-08-15T23:00:00Z`), or a date-only string (such as `2024-08-15`). With no timezone information provided, you may need extra knowledge to determine the actual timezone for the former two types, such as where the author is based, and what the timezone is in that region (not every country has only a single timezone like in China), which sometimes could be trivial. Besides, as people from all over the world could be using the same package, I personally prefer a "non-biased" timezone like UTC to minimize the side-effects from the timezone differences, for example the one-day offset between UTC+12 and UTC-12.

> Otherwise, if that release time is before 08:00, it will end up in the WinGet manifest as the previous day, which contradicts to what most users (who are in China) see on the official webpage or in the program.

I reckon no publisher would release a new version at midnight, according to the common sense and the automation log. In terms of WeType, I guess they didn't convert the timezone to UTC before converting the time to Unix timestamp.
