### ISSUE TITLE
Tencent.QQ version changed to real version

### ISSUE THREAD

**Issue by stevenlele** [SpecterShell/Dumplings#18]
https://github.com/SpecterShell/Dumplings/actions/runs/10609037350/job/29404100539#step:6:1077

**Comment by SpecterShell** [comment]
Well, the version scheme of the URL has been changed back and forth for so many times in the past months. I will make a better script for this package.

**Comment by SpecterShell** [comment]
Resolved in https://github.com/SpecterShell/Dumplings/commit/d777605c502f235e7b2c7eddbe8c5606933b1c5f
