### ISSUE TITLE
Please stop tracking QuadSpinner.Gaea

### ISSUE THREAD

**Issue by daxpandhi** [SpecterShell/Dumplings#19]
Appreciate you trying to automate this, but we prefer to submit manifests to winget at our own pace after our own set of checks. 

The last automated update you made used the wrong hash and caused a lot of trouble for us as we were NOT going to submit that version for winget. The version would have been updated in-place with a new exe and then updated on winget later on.

In any case, we would like to use our own system for pushing winget updates. So please remove this task from your bot as soon as possible.

Thanks.

**Comment by SpecterShell** [comment]
Removed. Sorry for the inconvenience.
